Repository SebastianStehle/mjml-net, pull requests merged in 2022-03, with the labels that each got.

#29 Text
  Mjml.Net/Components/Body/TextComponent.cs
  Mjml.Net/Extensions/HtmlRendererExtensions.cs
  Mjml.Net/Helpers/ConditionalTags.cs
  Mjml.Net/INode.cs
  Mjml.Net/MjmlRenderContext.cs
  Mjml.Net/MjmlRenderer.cs
  Tests/MjmlRenderContextTests.cs
  Tests/Tests.csproj
  Tests/Tests/Text.html
  Tests/Tests/TextWithHtml.html
  Tests/TextTests.cs
Labels: WIP

#47 Column
  Mjml.Net/Components/Body/ColumnComponent.cs
  Mjml.Net/MjmlRenderer.cs
  Tests/ColumnTests.cs
  Tests/Tests.csproj
  Tests/Tests/ColumnFour.html
  Tests/Tests/ColumnOne.html
  Tests/Tests/ColumnOneWithPadding.html
  Tests/Tests/ColumnThree.html
  Tests/Tests/ColumnTwo.html
Labels: REVIEW

#46 Moved NodeExtensions to Extensions namespace.
  Mjml.Net/Components/Body/ColumnComponent.cs
  Mjml.Net/Components/Body/DividerComponent.cs
  Mjml.Net/Components/Body/GroupComponent.cs
  Mjml.Net/Components/Body/HeroComponent.cs
  Mjml.Net/Components/Body/ImageComponent.cs
  Mjml.Net/Components/ContainerWidth.cs
  Mjml.Net/Extensions/NodeExtensions.cs
Labels: REVIEW

#31 Section
  Mjml.Net/Components/Body/SectionComponent.cs
  Mjml.Net/Extensions/StringExtensions.cs
  Mjml.Net/MjmlRenderer.cs
  Tests/CssClassesExtensionsTests.cs
  Tests/SectionTests.cs
  Tests/Tests.csproj
  Tests/Tests/Section.html
  Tests/Tests/SectionWithBackgroundColor.html
  Tests/Tests/SectionWithBackgroundImage.html
Labels: WIP

#48 Conditional Tags
  Mjml.Net/Components/Body/SectionComponent.cs
  Mjml.Net/Components/Body/TextComponent.cs
  Mjml.Net/Extensions/HtmlRendererExtensions.cs
  Mjml.Net/Helpers/ConditionalTags.cs
  Tests/MjmlRenderContextTests.cs
Labels: REVIEW

#57 Benchmarks
  Mjml.Net.Benchmarking/Mjml.Net.Benchmarking.csproj
  Mjml.Net.Benchmarking/Program.cs
  Mjml.Net.Benchmarking/TemplateBenchmarks.cs
  Mjml.Net.Benchmarking/Templates/Amario.mjml
  Mjml.Net.Benchmarking/Templates/Austin.mjml
  Mjml.Net.Benchmarking/Templates/Sphero.mjml
  Mjml.Net.sln
  TestRunner/Austin.mjml
  TestRunner/Program.cs
  TestRunner/Sphero.mjml
  TestRunner/TestRunner.csproj
Labels: review

#68 Html-Entities Readme
  README.md
Labels: review

#79 mj-table
  Mjml.Net/Components/Body/TableComponent.cs
  Mjml.Net/MjmlRenderer.cs
  Tests/TableTests.cs
  Tests/Tests.csproj
  Tests/Tests/Table.html
  Tests/Tests/TablePercent.html
  Tests/Tests/TablePixels.html
Labels: review

#74 Added more templates to benchmarking
  Mjml.Net.Benchmark/Mjml.Net.Benchmark.csproj
  Mjml.Net.Benchmark/Program.cs
  Mjml.Net.Benchmark/TemplateBenchmarks.cs
  Mjml.Net.Benchmark/Templates/Amario.mjml
  Mjml.Net.Benchmark/Templates/Arturia.mjml
  Mjml.Net.Benchmark/Templates/Austin.mjml
  Mjml.Net.Benchmark/Templates/BlackFriday.mjml
  Mjml.Net.Benchmark/Templates/Card.mjml
  Mjml.Net.Benchmark/Templates/Christmas.mjml
  Mjml.Net.Benchmark/Templates/HappyNewYear.mjml
  Mjml.Net.Benchmark/Templates/ManyHeroes.mjml
  Mjml.Net.Benchmark/Templates/OnePage.mjml
  Mjml.Net.Benchmark/Templates/Proof.mjml
  Mjml.Net.Benchmark/Templates/Racoon.mjml
  Mjml.Net.Benchmark/Templates/Reactivation.mjml
  Mjml.Net.Benchmark/Templates/RealEstate.mjml
  Mjml.Net.Benchmark/Templates/Recast.mjml
  Mjml.Net.Benchmark/Templates/Receipt.mjml
  Mjml.Net.Benchmark/Templates/Referral.mjml
  Mjml.Net.Benchmark/Templates/SpheroDroids.mjml
  Mjml.Net.Benchmark/Templates/SpheroMini.mjml
  Mjml.Net.Benchmark/Templates/UGGRoyale.mjml
  Mjml.Net.Benchmark/Templates/Welcome.mjml
  Mjml.Net.Benchmark/Templates/Worldly.mjml
  Mjml.Net.Benchmark/TestRunner.cs
  Mjml.Net.Benchmarking/Mjml.Net.Benchmarking.csproj
  Mjml.Net.Benchmarking/Program.cs
  Mjml.Net.Benchmarking/TemplateBenchmarks.cs
  Mjml.Net.Benchmarking/Templates/Amario.mjml
  Mjml.Net.Benchmarking/Templates/Sphero.mjml
  Mjml.Net.sln
  README.md
  TestRunner/Austin.mjml
  TestRunner/Program.cs
  TestRunner/TestRunner.csproj
Labels: enhancement

#87 mj-carousel
  Mjml.Net/Components/Body/CarouselComponent.cs
  Mjml.Net/Components/Body/CarouselImageComponent.cs
  Mjml.Net/Mjml.Net.csproj
  Mjml.Net/MjmlRenderer.cs
  Tests/Components/CarouselTests.cs
  Tests/Components/Outputs/Carousel.html
  Tests/Components/Outputs/CarouselHeadStyles.html
  Tests/Components/Outputs/CarouselIconWidth.html
  Tests/Components/Outputs/CarouselImageWithHref.html
  Tests/Components/Outputs/CarouselImagesFive.html
  Tests/Components/Outputs/CarouselImagesOne.html
  Tests/Components/Outputs/CarouselImagesTwo.html
  Tests/Components/Outputs/CarouselThumbnailWidth.html
  Tests/Internal/AssertHelpers.cs
  Tests/Tests.csproj
Labels: help wanted, in progress

#100 Preserve white spaces in `RenderRaw()`
  Mjml.Net/Component.cs
  Tests/Components/Outputs/TextWithHtmlAndWhitespace.html
  Tests/Components/TextTests.cs
  Tests/Tests.csproj
Labels: bug, review

#102 Set current culture.
  Mjml.Net/IHtmlAttrRenderer.cs
  Mjml.Net/IHtmlClassRenderer.cs
  Mjml.Net/IHtmlRenderer.cs
  Mjml.Net/IHtmlStyleRenderer.cs
  Tests/HtmlRenderTests.cs
Labels: bug

#104 Mjml.Net Fix NuGet Package Versioning
  Mjml.Net/Mjml.Net.csproj
Labels: bug
